# Generated by Django 6.0.5 on 2026-05-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='required_skills',
            field=models.CharField(default='General', max_length=200),
            preserve_default=False,
        ),
    ]
