# Generated by Django 6.0.5 on 2026-05-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_opportunityapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
